stages:
    - build
    - style
    - test
    - deploy

building:
    stage: build
    tags:
      - build
    script:
      - cd src/cat
      - make s21_cat
      - cd ../grep
      - make s21_grep
    artifacts:
      paths:
        - src/cat/s21_cat
        - src/grep/s21_grep
      expire_in: 30 days
    after_script:
            - sh src/notify.sh "build"

style_tests:
    stage: style
    tags:
      - style
    script:
      - cd src/cat
      - make style_tests
      - cd ../grep
      - make style_tests
    after_script:
            - sh src/notify.sh "style_tests"

code_tests:
    stage: test
    tags:
      - test
    script:
      - cd src/cat
      - make tests
      - cd ../grep
      - make tests
    when: on_success
    after_script:
            - sh src/notify.sh "code_tests"

deploy:
    stage: deploy
    tags:
      - deploy
    script:
      - bash src/copy.sh
    when: manual
    after_script:
            - sh src/notify.sh "deploy"

